//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kawiarnia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KawiarniaEntities : DbContext
    {
        public KawiarniaEntities()
            : base("name=KawiarniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coffee> Coffee { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Milk> Milk { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
    }
}
