//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kawiarnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public Nullable<int> CustromerId { get; set; }
        public Nullable<int> CoffeeId { get; set; }
        public Nullable<int> MilkId { get; set; }
    
        public virtual Coffee Coffee { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Milk Milk { get; set; }
    }
}
